### ISSUE TITLE
Unloading libssh2lv.dll problem

### ISSUE THREAD

**Issue by Kateshikikato84** [fieldrndservices/libssh2lv#15]
Hello,

I have problem with unloading `libssh2lv.dll` in LabView. When i use [this](https://knowledge.ni.com/KnowledgeArticleDetails?id=kA00Z0000019O6eSAE&l=pl-PL) example from `Ni.COM` about `How to Load and Unload a DLL Dynamically in LabView` it doesn't Unload properly with `initialize` function. I cannot remove or replace this dll from harddrive until LabView is Closed.
The problem first occured when I used `fieldrndservices/libssh2-labview` toolkit and example from its `README.md`. After executing the code something was still holding this library until LabView is closed. 
I don't think it should act like that - these shutdown functions should unload this library properly but it doesn't.
Is there any chance to fix it?

**Comment by volks73** [comment]
Thank you for the question. I am sorry you have encountered this problem.

I have tried and tried to get the unload DLL to work for this toolkit. I have seen that example from NI.com and I periodically try to implement DLL unloading when I work on this toolkit, but I have never been able to get the DLL unloading to work.

So, at this time, this is a "wont fix" unless someone else is able to figure out the implementation and provides a Pull Request (PR), which I will excitedly accept and merge into the toolkit.
