### ISSUE TITLE
Libssh2 new release

### ISSUE THREAD

**Issue by jchretien** [fieldrndservices/libssh2lv#16]
Hi!
I'm having trouble using the labview library, the problem could be with my ssh server... I noticed a major update on libssh2 1.11 May 30 2023 and your DLL is from 2022.

I'm having trouble with VS 2019, I'm not much familiar with that... Is it a good idea to recompile the DLL to benefit the libssh2 updates or its worthless?

I'll see where I can get with visual studio, it's a good learning opportunity for me actually. But if you may release a new build I'd be more than happy.

**Comment by volks73** [comment]
Thank you for your question and interest in the libssh2lv library. I have looked over the [changelog](https://libssh2.org/changes.html) for libssh2 v1.11. It is difficult to know if building a new DLL is a worthwhile endeavor, but the v1.11 release has many changes with interesting new features. The v1.11 release should be backwards compatible, too. 

Without more details about your issue, I cannot provide any guidance if building a new DLL would resolve your issue.

I am not opposed to building a new DLL, but I do not have time or capacity at the moment to do so myself. I cannot say when I will have time and capacity to build a new DLL. Unfortunately, it is not automated, but it is well-documented.

**Comment by jchretien** [comment]
Thanks for your reply. A colleague managed to re-compile the dll but it didn't help.

But I found the issue, it's likely caused by my ssh server, I had to put a carriage return after my commands, not a line feed.

**Comment by volks73** [comment]
I am happy to hear you were able to resolve your issue. I am going to close this issue and I will create a separate issue to track creating a new release based on the latest release for libssh2. Thank you.
