### ISSUE TITLE
Windows XP Supported?

### ISSUE THREAD

**Issue by jchretien** [fieldrndservices/libssh2lv#17]
I'm trying to use the library in windows xp, is it suppose to work? I'm getting this error.

![image](https://github.com/fieldrndservices/libssh2lv/assets/16946356/320ab381-32b7-4276-959b-6f455ae8941d)

Thanks

**Comment by volks73** [comment]
The error message indicates that a DLL compiled for Windows 7 or newer is not backwards compatible with Windows XP, but this is largely a guess as I have never encountered that error before.

In theory, if the underlying libssh2 library can be compiled for Windows XP, then there is a possibility for this library to be compiled for Windows XP. However, I do not have access to a Windows XP machine, so unfortunately I cannot support Windows XP. I also do not have experience compiling DLLs on Windows XP.

**Comment by jchretien** [comment]
I tried to re-compile for XP and still I'm getting similar errors... I decided to install Win7 on the PXI controller, your library is great and XP is 20 years old, time to move a step forward ;)
