### ISSUE TITLE
Bytes available at port

### ISSUE THREAD

**Issue by rdp137** [fieldrndservices/libssh2lv#9]
Is there a way to determine if there are bytes available at the port before doing a read or is my only option to try to read and use the timeout output?

**Comment by volks73** [comment]
Thank you for your question and usage of the LIBSSH2 for LabVIEW toolkit.

The "bytes available at port" is a VISA function. SSH communication is TCP-based, and the LabVIEW TCP API is relatively "higher level" implementation that does not include a similar "bytes available at port" function. I found, "[how to get the number of bytes at ethernet port using tcp/ip?](https://forums.ni.com/t5/LabVIEW/how-to-get-the-number-of-bytes-at-ethernt-port-using-tcp-ip/td-p/1012674?profile.language=en)", discussion on NI's forums that is essentially the same question. 

However, the [libssh2](https://libssh2.org) library does provide a "non-blocking" mode, which would avoid the need for using a timeout. [According to libssh2's documentation](https://libssh2.org/libssh2_session_set_blocking.html):

>If a read is performed on a session with no data currently available, a blocking session will wait for data to arrive and return what it receives. A non-blocking session will return immediately with an empty buffer. If a write is performed on a session with no room for more data, a blocking session will wait for room. A non-blocking session will return immediately without writing anything.

A blocking session would require the usage of the timeout, but a non-blocking session would immediately return with whatever bytes are available. Thus, you would need to create your own VI that enables the non-blocking mode for the SSH communication in combination with the Read VI for a channel and a "buffer" string to mimic the "bytes available at port".

Please see the [Read-Execute-Print-Loop with a Raspberry Pi](https://github.com/fieldrndservices/libssh2-labview/blob/main/src/Examples/Read-Execute-Print-Loop%20with%20a%20Raspberry%20Pi.vi) example, which is available in the Example Finder as well. You do not need a Raspberry Pi to use this example. I just get a lot of questions about communicating with a Raspberry Pi from LabVIEW over SSH and wanted a "go-to" example for the Raspberry Pi. This example uses the non-blocking mode and the Read.vi in a separate loop and could be a good starting point.

Tangentially, many consider using the "bytes available at port" VISA function bad form/practice and its usage is usually an indicator of a design flaw for communication between devices. This is discussed in the above mentioned NI forum thread. But, you may not have control over the communication protocol.
